name: Generate Snake Game

on:
  schedule: 
      - cron: "0 0 * * *"  # Executa a cada dia à meia-noite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Verifica o repositório
      - name: Checkout
        uses: actions/checkout@v2

      # Gera a animação da cobrinha e salva como snake.svg
      - name: Generate Snake
        uses: Platane/snk@v2
        with:
          github_user_name: LuizTakahashiii  # Substitua pelo seu nome de usuário
          svg_out_path: dist/snake.svg

      # Publica o arquivo snake.svg na branch `output`
      - name: Push Snake to output branch on GitHub
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
